# General settings
name: STTMT-S
use_tb_logger: True #true
model: STTMT
scale: 4
gpu_ids: [0,1]

# Datasets
dataset:
  name: Vimeo90k_septuplet
  random_reverse: true #false
  dataroot_HR: /mnt/Temp_new/QXT/VSRdataset/Vimeo-90K/vimeo_septuplet/vimeo7_train_GT.lmdb
  dataroot_LR: /mnt/Temp_new/QXT/VSRdataset/Vimeo-90K/vimeo_septuplet_matlabLRx4_train/vimeo7_train_LR7.lmdb
  cache_keys: /mnt/Temp_new/QXT/VSRdataset/Vimeo-90K/vimeo_septuplet/vimeo7_train_GT.lmdb/Vimeo7_train_keys.pkl

  num_frames: 7
  use_shuffle: true
  n_workers: 6  # per GPU
  batch_size: 12
  crop_size: 256
  image_shape: [3, 256, 448]
  use_flip: true
  use_rot: true

# Network structures
network:
  embed_dim: 96
  depths: [4, 4, 4, 4, 4, 4, 4, 4]
  num_heads: [2, 4, 8, 16, 16, 8, 4, 2]
  window_sizes: [[4,4], [4,4], [4,4], [4,4], [4,4], [4,4], [4,4], [4,4]]
  back_RBs: 10

# Path
path:
  pretrain_model: ~ 
  strict_load: true # false
  resume_state: ~

# Training settings
train:
  lr: 0.0002
  lr_scheme: CosineAnnealingLR_Restart
  beta1: 0.9
  beta2: 0.99
  niter: 2000000
  warmup_iter: -1 # 5000  # -1: no warm up
  T_period: [400000, 800000, 1200000, 1600000]
  restarts: [400000, 800000, 1200000]
  restart_weights: [0.5, 0.5, 0.5]
  eta_min: !!float 1e-7

  val_freq: !!float 5e3

  manual_seed: 0

# Logger
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3
