# General settings
name: STTMT-S
use_tb_logger: false #true
model: STTMT
scale: 4
gpu_ids: [4]

# Dataset
dataset:
  name: REDS4
  dataset_root: /mnt/Temp_new/QXT/dataset/REDS4
  num_out_frames: 7

# Network structures5
network:
  embed_dim: 96
  depths: [4, 4, 4, 4, 4, 4, 4, 4]
  num_heads: [2, 4, 8, 16, 16, 8, 4, 2]
  window_sizes: [[4,4], [4,4], [4,4], [4,4], [4,4], [4,4], [4,4], [4,4]]
  back_RBs: 10

# Path
path:
  pretrain_model: ~
  strict_load: False
  output_dir: ./results